name: Release

on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: true

jobs:
  release-please:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.release.outputs['version'] }}
      pr: ${{ steps.release.outputs['pr'] }}
      tag-name: ${{ steps.release.outputs['tag_name'] }}
      release_created: ${{ steps.release.outputs['release_created'] }}

    steps:
      - name: Release with release-please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
            token: ${{ secrets.RELEASE_TOKEN }}
            config-file: .github/release-please/config.json
            manifest-file: .github/release-please/manifest.json

      - name: Show output from release-please
        env:
          RELEASE_PLEASE_OUTPUT: ${{ toJSON(steps.release.outputs) }}
        run: echo "${RELEASE_PLEASE_OUTPUT}" | jq

  upload-archive:
      if: ${{ needs.release-please.outputs.release_created }}

      runs-on: ubuntu-latest
      needs:
          - release-please

      permissions:
          contents: write

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Build archive
          run: tar -czf module.tar.gz README.md

        - name: Upload archive
          uses: softprops/action-gh-release@v1
          with:
            tag_name: ${{ needs.release-please.outputs.tag-name }}
            files: |
              ./module.tar.gz
